/*
 * This file was generated by qdbusxml2cpp-fix version 0.8
 * Command line was: qdbusxml2cpp-fix -c KWin -p generated/org_kde_kwin ../xml/org.kde.KWin.xml
 *
 * qdbusxml2cpp-fix is Copyright (C) 2016 Deepin Technology Co., Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ORG_KDE_KWIN_H
#define ORG_KDE_KWIN_H

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

#include <DBusExtendedAbstractInterface>
#include <QtDBus/QtDBus>


/*
 * Proxy class for interface org.kde.KWin
 */
class __KWinPrivate;
class __KWin : public DBusExtendedAbstractInterface
{
    Q_OBJECT

public:
    static inline const char *staticInterfaceName()
    { return "org.kde.KWin"; }

public:
    explicit __KWin(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~__KWin();

public Q_SLOTS: // METHODS

Q_SIGNALS: // SIGNALS
    void PresentWindowStateChanged(bool state);
    // begin property changed signals

public Q_SLOTS:
    void CallQueued(const QString &callName, const QList<QVariant> &args);

private Q_SLOTS:
    void onPendingCallFinished(QDBusPendingCallWatcher *w);

private:
    __KWinPrivate *d_ptr;
};

namespace org {
  namespace kde {
    typedef ::__KWin KWin;
  }
}
#endif
